import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

function generateHash(input: string){
  const arr = input.replace(/ /g,"").split("")

  let result = 0

  for(let i=0; i < arr.length; i++){
    result = result + input.charCodeAt(i)
  }

  return {
    first: result,
    second: result * arr.length,
  }
}

export default function Home() {
  const [name,setName] = useState("")

  function generateName(input: string){
    const hash = generateHash(input)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Wu-Tang Clan Name Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="form">
          <input placeholder='Your name' onChange={(e)=> setName(e.target.value)} />
          <button onClick={() => generateName(name)}>Generate name</button>
        </div>
      </main>
    </div>
  )
}
